### ISSUE TITLE
bro how install this

### ISSUE THREAD

**Issue by JustADude123** [Chick2D/neofetch-themes#1]
i am on windows peole tell to install thim

**Comment by Chick2D** [comment]
> i am on windows peole tell to install thim

literally find the config file and change it you dumbass

**Comment by LordLucass** [comment]
> Neofetch does not support Windows.

![image](https://user-images.githubusercontent.com/47451974/150212076-2bde0138-0552-4894-92fb-fa25ebbc5241.png)

**Comment by yonderbread** [comment]
[youre welcome](https://raw.githubusercontent.com/kiedtl/winfetch/master/winfetch.ps1)

**Comment by qualk** [comment]
Oh right, it's on Cygwin.
