### ISSUE TITLE
The icons don't work for me

### ISSUE THREAD

**Issue by FancyBaguette** [Chick2D/neofetch-themes#2]
The icons featured in "insert name" and "insert name 2 electric boogalo" configs do not work for me and appear bugged, as shown in the screenshot below. How to fix it?
![image](https://user-images.githubusercontent.com/63610278/138588436-293673d9-2435-4db5-bbf1-489dd45b01aa.png)

**Comment by RidgewayPlus** [comment]
Install all of them

**Comment by Chick2D** [comment]
Seems like you need a nerd font

from my experience, installing `ttf-material-design-icons-extended` works out most of the time, terminal emulators may play a role in this.

**Comment by ahmadhabibi14** [comment]
> Seems like you need a nerd font
> 
> from my experience, installing `ttf-material-design-icons-extended` works out most of the time, terminal emulators may play a role in this.

My neofetch still not show icon after I have downloaded that icon..
