### ISSUE TITLE
What Font do i need for the Icons to display properly?

### ISSUE THREAD

**Issue by OhaDerErste** [Chick2D/neofetch-themes#3]
![image](https://user-images.githubusercontent.com/77100649/149996615-b8518cf1-5425-4bb0-aae4-aa09cbfa13fc.png)
These one

**Comment by ant0n-anon** [comment]
okay but all joking aside i've been on an endless chase of trying to get these working.

![image](https://user-images.githubusercontent.com/76716724/154829346-39627cf1-b69f-4217-b7d6-3e2554b3f241.png)

**Comment by ant0n-anon** [comment]
i'm getting closer 
![image](https://user-images.githubusercontent.com/76716724/154829695-19bbecbd-57f1-4373-a493-b527f3de1473.png)

**Comment by 7ud** [comment]
How'd u get it rainbow?

**Comment by 7ud** [comment]
Nvm figured it out xd

**Comment by 7ud** [comment]
But yeah I can't get the icons to show at all

**Comment by 7ud** [comment]
Wait i think I found it it's called meslo nerd

**Comment by ant0n-anon** [comment]
![image](https://user-images.githubusercontent.com/76716724/159139562-5ecf0f47-a9cd-4931-8aad-d707ba063fde.png)

i'm getting closer

**Comment by yonderbread** [comment]
[Nerd fonts](https://aur.archlinux.org/packages/nerd-fonts-complete)? So, for `Meslo` as a nerd font, `Meslo Nerd Font` would probably be fit.

**Comment by Chick2D** [comment]
You just require any nerdfont as previously said, closing issue
