### ISSUE TITLE
Nerdfonts not workings - Alacritty and Terminator

### ISSUE THREAD

**Issue by CodingWithAnxiety** [Chick2D/neofetch-themes#45]
![image](https://user-images.githubusercontent.com/78890450/235968283-24e55c33-e89a-405a-9a77-7b1b2888c0ee.png)

I like this theme a lot. But the icons don't work 
:_:

I looked on the nerd-fonts symbol cheat sheet, and it says they're deprecated symbols

**Comment by CodingWithAnxiety** [comment]
Can I make a merge request that fixes them?

**Comment by hasecilu** [comment]
Yeah, for example I found this at https://www.nerdfonts.com/cheat-sheet
Just copy the new glyphs unicode

![image](https://github.com/Chick2D/neofetch-themes/assets/53124818/b9725cb6-d0b4-4346-8171-ffba7b31887b)
